In [2]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv(r"C:\Users\jay19\OneDrive\Desktop\messy_customer_sales_data.csv")

In [4]:
df.head()

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India

In [5]:
df.shape

(10200, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [7]:
df.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [8]:
df.isnull().sum()

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

In [9]:
df.shape

(10200, 12)

In [10]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [11]:
df['Customer_ID'].value_counts()

Customer_ID
CUST3374     2
CUST7749     2
CUST10800    2
CUST6588     2
CUST9062     2
            ..
CUST10204    1
CUST4647     1
CUST9548     1
CUST9966     1
CUST4812     1
Name: count, Length: 9000, dtype: int64

In [12]:
df[df['Customer_ID']=='CUST3374']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2914,CUST3374,Timothy Wallace,m,58.0,Bangalore,2024-03-08,2025-08-21,45779.0,1.0,glenn95@example.org,9687701793,India
3047,CUST3374,Timothy Wallace,m,58.0,bangalore,2024-03-08,2025-08-21,45779.0,1.0,glenn95@example.org,9687701793,India

In [13]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
--------------------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
--------------------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
--------------------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
--------------------------------------------------

## Handling Missing Values

In [59]:
df.dropna(subset=['Customer_ID'], inplace = True)

In [60]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date      0
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [61]:
df['Age'].unique()

array([ 52.,  51.,  62.,  40.,  41.,  43.,  18.,  26.,  32.,  22.,  59.,
        65.,  61.,  31.,  54.,  55.,  69.,  24.,  63.,  19.,  50.,  56.,
        36.,  68.,  38.,  27.,  57.,  23.,  25.,  66.,  28.,  30.,  46.,
        48.,  20.,  37.,  67.,  35.,  58.,  29.,  39.,  49.,  47.,  42.,
        44.,  64.,  53.,  60.,  45.,  21.,  34.,  33., 250.,   3.,  10.])

In [62]:
import re 
def extract_age(age) :
    age_num=re.findall('[0-9]+',str(age))
    if len(age_num) >0  :
        return age_num[0]
    else :
        return age

df['Age'] = df['Age'].apply(lambda x : extract_age(x))

In [63]:
df['Age'].unique()

array(['52', '51', '62', '40', '41', '43', '18', '26', '32', '22', '59',
       '65', '61', '31', '54', '55', '69', '24', '63', '19', '50', '56',
       '36', '68', '38', '27', '57', '23', '25', '66', '28', '30', '46',
       '48', '20', '37', '67', '35', '58', '29', '39', '49', '47', '42',
       '44', '64', '53', '60', '45', '21', '34', '33', '250', '3', '10'],
      dtype=object)

In [64]:
df_age = df[df['Age'] != 'nan years']['Age']

In [65]:
age_median = int(df_age.dropna().astype('int64').median())

In [66]:
age_median

43

In [67]:
df = df.replace('nan years' , age_median )

In [68]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

age_median = int(df['Age'].median())

df['Age'] = df['Age'].fillna(age_median)

print(df['Age'].isnull().sum())

0

In [69]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date      0
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [84]:
df['Purchase_Amount']=df['Purchase_Amount'].fillna(df['Purchase_Amount'].median() )

In [85]:
df['Feedback_Score']=df['Feedback_Score'].fillna(df['Feedback_Score'].median()  )

In [86]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date      0
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [97]:
for col in ['Gender', 'City', 'Country']:
    df[col] = df[col].fillna(df[col].mode()[0])

In [98]:
df['Last_Purchase_Date'].ffill(inplace = True)

C:\Users\jay19\AppData\Local\Temp\ipykernel_4604\2735699428.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Last_Purchase_Date'].ffill(inplace = True)

In [99]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [100]:
df['Gender'].unique()

array(['male', 'female'], dtype=object)

In [101]:
df['Gender']=df['Gender'].str.lower().str.strip()

In [102]:
df['Gender'] = df['Gender'].replace({'m':'male','f':'female'})

In [103]:
df['Gender'].unique()

array(['male', 'female'], dtype=object)

In [109]:
df['City'] = df['City'].str.lower().str.strip()

In [118]:
df['City'].unique()

array(['kolkata', 'hyderabad', 'chennai', 'bangalore', 'mumbai', 'delhi'],
      dtype=object)

In [125]:
df['Country']=df['Country'].str.lower()

0        None
1        None
2        None
3        None
4        None
         ...
10194    None
10195    None
10197    None
10198    None
10199    None
Name: Country, Length: 9177, dtype: object

In [124]:
df['Country'].unique()

array([None], dtype=object)

In [121]:
df['Country'] = df['Country'].replace({'ind':'india'})

In [128]:
df['Country'].unique()

array(['india'], dtype=object)

In [127]:
df['Country'] = df['Country'].fillna('india')

In [137]:
df[df.duplicated()].shape

(0, 12)

In [136]:
df.drop_duplicates(inplace = True)

In [140]:
df[df['Customer_ID']=='CUST9534']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
3528,CUST9534,Melissa Jones,male,53,kolkata,2021-08-26,2025-08-11,21959.0,8.0,cassandrahill@example.net,7734467854,india
9005,CUST9534,Melissa Jones,male,53,kolkata,2021-08-26,2025-01-05,21959.0,8.0,cassandrahill@example.net,7734467854,india

In [145]:
df.drop_duplicates(subset=['Customer_ID'] , keep = 'last' ).shape

(9000, 12)

## handling datatypes

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9000 non-null   object
 1   Name                9000 non-null   object
 2   Gender              9000 non-null   object
 3   Age                 9000 non-null   int64
 4   City                9000 non-null   object
 5   Signup_Date         9000 non-null   object
 6   Last_Purchase_Date  9000 non-null   object
 7   Purchase_Amount     9000 non-null   float64
 8   Feedback_Score      9000 non-null   float64
 9   Email               9000 non-null   object
 10  Phone_Number        9000 non-null   int64
 11  Country             9000 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 914.1+ KB

In [147]:
df['Age']=df['Age'].astype('int64')

In [148]:
df['Signup_Date']=pd.to_datetime(df['Signup_Date'])

In [149]:
df['Last_Purchase_Date']=pd.to_datetime(df['Last_Purchase_Date'])

In [150]:
df.dtypes

Customer_ID                   object
Name                          object
Gender                        object
Age                            int64
City                          object
Signup_Date           datetime64[ns]
Last_Purchase_Date    datetime64[ns]
Purchase_Amount              float64
Feedback_Score               float64
Email                         object
Phone_Number                   int64
Country                       object
dtype: object

### handling outliers

In [153]:
from scipy.stats import zscore
import numpy as np

z_score = np.abs(zscore(df[['Age','Purchase_Amount']]))

In [154]:
df_clean = df[~(z_score>3).any(axis=1)]

In [155]:
df_clean.shape

(8990, 12)

In [156]:
df.to_csv('df_clean.csv', index=False)

In [157]:
import os
print(os.getcwd())

C:\Users\jay19\100_days_of_ML